### ISSUE TITLE
请问你这个跟原作者的有什么差异？

### ISSUE THREAD

**Issue by chenyu1990** [lvxiaoxing/umi-plugin-multi-panels#2]
readme里没写，请教一下。

**Comment by lvxiaoxing** [comment]
原作者没有留一些相应的槽，比如【强制关闭所有标签并且不打开默认标签页】的hook，并且在使用的过程中有遇见两个相同的标签同处于激活状态的问题，我就改了一些，主要是根据当前开发项目的需要进行一些修改
